Katello/bastion

- app/assets/javascripts/bastion/bastion.module.js
Prior to this commit we were removing any query string
parameters provided by ui-sref to the state.  This commit
changes the logic so we only preserve and update the
$location.search (i.e. query string parameters) if there
is a search string.
http://projects.theforeman.org/issues/9041
> Fixes #9041: only preserve search strings across states.

- app/assets/javascripts/bastion/components/path-selector.directive.js
- app/assets/javascripts/bastion/components/views/path-selector.html
- test/components/path-selector.directive.test.js
IE wasn't selecting paths properly when clicking, item.selected was
not being set to true when seleted.  This commit ensures that the
path is selected by setting item.selected manually.
http://projects.theforeman.org/issues/9345
https://bugzilla.redhat.com/show_bug.cgi?id=1168457
> Fixes #9345: ensure selection of paths in IE, bz 1168457.

- app/views/bastion/layouts/application.html.erb
- lib/bastion.rb
Plugins can add configuration that is loaded via BastionConfig by
specifying during declaration:
Bastion.register_plugin(
:name => 'Foo',
:config => {
'myBar' => 'isFoo'
}
)
> Fixes #9399: Allow plugins to add configuration entries.

- app/assets/javascripts/bastion/components/path-selector.directive.js
- app/assets/javascripts/bastion/components/views/path-selector.html
- test/components/path-selector.directive.test.js
Commits cc61cf4 and c799764 introduced changes to the path-selector
that are not needed.  The issue was on the katello side and has been
addressed with https://github.com/Katello/katello/pull/5057.
http://projects.theforeman.org/issues/9345
https://bugzilla.redhat.com/show_bug.cgi?id=1168457
> Refs #9345: revert IE specific changes to path selector, BZ1168457.

- app/assets/javascripts/bastion/components/nutupane.factory.js
- app/assets/javascripts/bastion/layouts/details-nutupane.html
- app/assets/javascripts/bastion/layouts/nutupane.html
- app/assets/stylesheets/bastion/nutupane.less
Only show the nutupane loading indicator on initial load, search,
and refresh instead of every time the rows are updated.
http://projects.theforeman.org/issues/5339
https://bugzilla.redhat.com/show_bug.cgi?id=1199267
> Fixes #5339: only display loading on refresh BZ 1199267.

- app/assets/javascripts/bastion/components/nutupane-table.directive.js
The cloned nutupane table was being shown when there
were no rows in the table.  This commit hides the cloned
table if there are no rows.
http://projects.theforeman.org/issues/9930
See also:  https://bugzilla.redhat.com/show_bug.cgi?id=1206611
> Fixes #9930: hide cloned table when no rows.

- app/assets/javascripts/bastion/components/bst-table.directive.js
- app/assets/javascripts/bastion/components/nutupane-table.directive.js
There was some non-performant JS that was causing nutupane
to be really slow when there were lots of rows in a table,
namely triggering resize on each row inserted into the table.
This commit replaces the slow JS with an approach that is more
in performant and more in line with Angular JS best practices.
http://projects.theforeman.org/issues/9729
https://bugzilla.redhat.com/show_bug.cgi?id=1161630
> Fixes #9729: speed up nutupane by removing JS BZ 1161630.

- app/assets/stylesheets/bastion/nutupane.less
Break lines on words to avoid overlap of long words on labels and values.
http://projects.theforeman.org/issues/8260
https://bugzilla.redhat.com/show_bug.cgi?id=1142763
> Fixes #8260: prevent wrapping text for info label and value, BZ1142763.

- app/assets/javascripts/bastion/components/bst-infinite-scroll.directive.js
- test/components/bst-infinite-scroll.directive.test.js
We were triggering the resize event when more rows are added but
were not ensuring that we load until scroll when that happens.  This
commit ensures that we load until there is a scrollbar.
http://projects.theforeman.org/issues/10502
https://bugzilla.redhat.com/show_bug.cgi?id=1206704
> Fixes #10502: ensure enough results to scroll on resize, BZ1206704.

- app/assets/javascripts/bastion/components/bst-infinite-scroll.directive.js
Firefox apparently doesn't trigger a resize event on page load
and chrome does.  The changes in ecf1756d were relying on this
initial resize event to load the results.  This commit adds
back the inital load.
http://projects.theforeman.org/issues/10567
https://bugzilla.redhat.com/show_bug.cgi?id=1223562
> Fixes #10567: add back code to trigger initial load, BZ 1223562.

- app/assets/javascripts/bastion/components/nutupane.factory.js
- app/assets/javascripts/bastion/layouts/details-nutupane.html
- app/assets/javascripts/bastion/layouts/nutupane.html
- bower.json
- vendor/assets/javascripts/bastion/ngInfiniteScroll/ng-infinite-scroll.js
After replacing our own infinite scroll with ngInfiniteScroll
we weren't checking to see if scroll was needed after nutupane
results were loaded.  This could cause the display of only one
set of results on larger screens.  This commit forces ngInfiniteScroll
to recheck if a scroll is needed after results are loaded.
http://projects.theforeman.org/issues/10515
> Fixes #10515: check if scroll is needed after results are loaded.

- app/assets/javascripts/bastion/components/views/path-selector.html
This change is necessary because we were previously binding to the result of an expression instead of an expression itself. Thus, the ng-class directive would properly see the value of item.customClass but would not necessarily update based upon digest cycles.
with https://github.com/Katello/katello/pull/5444
> fixes #11076 - fixes starred environments promotion suggestions

- app/assets/javascripts/bastion/components/nutupane.factory.js
- test/components/nutupane.factory.test.js
This allows the searchKey to be changed after nutupane is declared and would fix the "bleeding"  of search parameters when there are two search boxes in view. 
To test in katello on packages -> repositories tab:
```
--- a/engines/bastion_katello/app/assets/javascripts/bastion_katello/packages/details/package-details-repositories.controller.js
+++ b/engines/bastion_katello/app/assets/javascripts/bastion_katello/packages/details/package-details-repositories.controller.js
@@ -26,7 +26,7 @@ angular.module('Bastion.packages').controller('PackageDetailsRepositoriesControl
$scope.detailsTable = repositoriesNutupane.table;
$scope.detailsTable.initialLoad = false;
repositoriesNutupane.masterOnly = true;
-        repositoriesNutupane.searchKey = 'repositoriesSearch';
+ …
```
> Fixes #11289 - nutupane details pages use search get param for searching

- app/assets/stylesheets/bastion/bastion.less
- app/assets/stylesheets/bastion/typography.less
Ensure text is wrapped in modals and alerts by creating
and using a wordwrap mixin.
http://projects.theforeman.org/issues/11831
https://bugzilla.redhat.com/show_bug.cgi?id=1205047
> Fixes #11831: wrap text in modal and alerts BZ1205047.

- config/routes.rb
I was seeing ```/bastion/:bastion_page``` instead of ```/:bastion_page ```in routes
> Fixes #12604 - update bastion routes for rails 4

- lib/bastion/engine.rb
To avoid the option development.rb config.assets.raise_runtime_errors
raise errors on Katello because the bastion assets are not loaded,
foreman will have to find them and add them to assets.precompile.
In order for foreman to find the assets paths, the initializer that
contains this settings needs to be named configure_assets and return the
SETTINGS[:bastion] hash
> Fixes #13108 -  Add assets to precompile in engine

- app/assets/javascripts/bastion/components/bst-global-notification.directive.js
- app/assets/javascripts/bastion/components/global-notification.service.js
- app/assets/javascripts/bastion/components/views/bst-alerts.html
- app/assets/javascripts/bastion/components/views/bst-global-notification.html
- app/assets/javascripts/bastion/layouts/nutupane.html
- test/components/bst-alerts.directive.test.js
- test/components/bst-global-notification.directive.test.js
- test/components/global-notification.service.test.js
This adds global notifications, I will open a separate PR that converts Katello to use global notifications, as this breaks functionality in Katello.
> Fixes #13116 - Add global notifications

- app/assets/javascripts/bastion/components/views/bst-alert.html
- app/assets/stylesheets/bastion/overrides.scss
It looks like the patternfly icons have changed their [names](https://www.patternfly.org/styles/icons/)
This also fixes the message and icon not being inline.
> Fixes #13176 - Missing red x on error message

- app/assets/javascripts/bastion/features/bst-feature-flag.directive.js
To inject dependencies this way it should be "$inject" instead of
"$injector".
http://projects.theforeman.org/issues/14165
> Fixes #14165: fix typo on feature flag $inject.

- app/assets/javascripts/bastion/components/bst-container-scroll.directive.js
- test/components/bst-container-scroll.directive.test.js
The container scroll directive was not taking padding height into
account when determining the height of the container.  This commit
fixes that issue.
http://projects.theforeman.org/issues/14149
> Fixes #14149: use padding when determining container scroll height.

- app/assets/javascripts/bastion/bastion.module.js
$location double encodes links that are already encoded resulting
in double encoding of +s (which are valid in query strings as
spaces).  This commit prevents the double encoding of +s.
http://projects.theforeman.org/issues/14243
> Fixes #14243: don't encode '+' in query strings.

- app/assets/javascripts/bastion/components/nutupane.factory.js
We may not want to `sort_by` a value when it comes from associated models. If `bst-table-column` is also `sortable`,  it reverses order of items by default.
> Fixes #14524 - bst-table-column without value reverses column values

- app/assets/javascripts/bastion/components/bst-container-scroll.directive.js
- test/components/bst-container-scroll.directive.test.js
Fixing the container scroll directive by adding additional height
when the element appears further down the page.
http://projects.theforeman.org/issues/14578
> Fixes #14578: ensure container scroll element is of a usable size.

- app/assets/stylesheets/bastion/nutupane.scss
Ensure the color of the text in a bst-edit element within a
highlighted row is black.
http://projects.theforeman.org/issues/14904
> Fixes #14904: ensure black text for bst-edit inside of rows.

- app/assets/javascripts/bastion/components/bst-table.directive.js
If rows have already been selected we should maintain the count of rows
between states.  This problem is commonly seen in the details-nutupane
tables.
http://projects.theforeman.org/issues/15027
> Fixes #15027: maintain number of selected rows between states.

- app/assets/javascripts/bastion/bastion.module.js
We were infinitely redirecting on sub-states that didn't exist.  This
commit redirects to a 404 page if a child state is not found.
http://projects.theforeman.org/issues/15352
> Fixes #15352: redirect to a 404 page if state does not exist.

- app/assets/javascripts/bastion/layouts/panel.html
Add support for a loading screen into the nutupane layout so that
a loading screen can be shown while the resource is loading.
http://projects.theforeman.org/issues/15544
> Fixes #15544: show a loading screen while resource is loading.

- app/assets/javascripts/bastion/components/bst-edit.directive.js
AngularJS changed the property 'then' to be on a parent class of
$resource so we need to update our checks to reflect this change.
http://projects.theforeman.org/issues/15936
> Fixes #15936: fix 'then' property check for $resources

- package.json
This fixes an issue with npm install breaking unable to find
throttleit.
> Fixes #16031: Pin phantomjs-prebuilt to 2.1.10

- app/assets/javascripts/bastion/routing.module.js
- app/views/bastion/layouts/application.html.erb
- app/views/bastion/layouts/application_ie.html.erb
This base requirement leads to test failures and errors in plugins
and modules inheriting.
> Fixes #16297: Don't require base for HTML5 mode

- bower.json
- vendor/assets/javascripts/bastion/ngUpload/ng-upload.js
This is a temporary fix to our local copy of ng-upload until https://github.com/twilson63/ngUpload/pull/133 is merged.
> Fixes #16296 - Pass content to errorCatcher

- app/assets/javascripts/bastion/components/bst-alert.directive.js
- app/assets/javascripts/bastion/components/views/bst-alert.html
- test/components/bst-alert.directive.test.js
We are fading out success alerts after three seconds regadless of
whether the user wants it to fade, this commit keeps the alert in place
if the mouse is over it.
http://projects.theforeman.org/issues/15081
> Fixes #15081: do not fade out success alert if it has focus.

- app/assets/javascripts/bastion/bastion.module.js
- app/assets/javascripts/bastion/layouts/404.html
- app/assets/javascripts/bastion/routing.module.js
- test/routing.module.test.js
Rather than redirecting to a 404 page it is a better experience to show
the user the 404 page within the application so that they may see the
URL they are getting a 404 page on.  This commit does just that.
http://projects.theforeman.org/issues/16727
> Fixes #16727: show 404 page within the application.

- package.json
This fixes an installation issue where a much older bower is used.
> Fixes #17049: Update grunt-bower-task to 0.5.Z

- app/assets/javascripts/bastion/bastion.js
- app/assets/javascripts/bastion/bastion.module.js
- app/assets/javascripts/bastion/components/bst-edit.directive.js
- app/assets/javascripts/bastion/components/bst-table.directive.js
- app/assets/javascripts/bastion/components/views/bst-edit.html
- app/assets/javascripts/bastion/layouts/page-with-breadcrumbs.html
- app/assets/javascripts/bastion/layouts/table.html
- app/assets/javascripts/bastion/layouts/two-column.html
- app/assets/stylesheets/bastion/bastion.scss
- app/assets/stylesheets/bastion/components.scss
- app/assets/stylesheets/bastion/forms.scss
- app/assets/stylesheets/bastion/overrides.scss
- app/assets/stylesheets/bastion/typography.scss
- app/views/bastion/layouts/application.html.erb
- bower.json
- vendor/assets/javascripts/bastion/angular-breadcrumb/angular-breadcrumb.js
Adding an alternative full page layout to nutupane that uses the breadcrumbs
from the previous commit.  Also adds a two column layout using bootstrap
3's grid system to replace the float method currently used.
http://projects.theforeman.org/issues/16534
Here is a page that points out some of the problems with our current approach (at 1280x800px):
On this page I am attempting to add an erratum to a filter in the table at the bottom.  Notice how small that table is and how much I would have to scroll if I had a lot of errata.  Also note the double scrollbars.
> Fixes #16534: add "non-nutupane" alternative. 

- app/assets/javascripts/bastion/bastion.module.js
We were saving $location.search() between state transitions which made
the search stay after changing to another state.  This commit removes
this logic.
http://projects.theforeman.org/issues/17099
> Fixes #17099: don't save $location.search() between states.

- app/assets/javascripts/bastion/bastion.module.js
- app/assets/javascripts/bastion/layouts/details-page-with-breadcrumbs.html
- app/assets/javascripts/bastion/layouts/partials/table.html
Breadcrumbs that include a $resource were not being displayed on page
reload.  This commit fixes that issue as well as makes the search
data-block of the table able to be replaced.
http://projects.theforeman.org/issues/17350
> Fixes #17350: ensure resource breadcrumbs show.

- app/views/bastion/layouts/application.html.erb
Apparently foreman's topbar JS requries a #content element to function
properly.  This commit adds that element so you don't see odd scrolling
behavior when the page is just small enough.
http://projects.theforeman.org/issues/17416
> Fixes #17416: add magic id so foreman topbar works properly.

- app/assets/javascripts/bastion/components/views/bst-alert.html
- app/assets/stylesheets/bastion/overrides.scss
The markup and styling for bst-alert was not following what patternfly
lays out as the proper markup.  This commit fixes the problems.
http://projects.theforeman.org/issues/17384
> Fixes #17384: bring bst-alert inline with patternfly.

- app/assets/javascripts/bastion/components/nutupane-table.directive.js
The tasks table wasn't being rendered correctly on load so fixing this
by triggering a reload event on the load of the nutupane table.
http://projects.theforeman.org/issues/17537
> Fixes #17537: trigger reize event on load to fix tasks table.

- app/assets/javascripts/bastion/layouts/table-with-header.html
The table-with-header layout is missing the "passthrough" data-blocks
messages and search-filter.  This commit adds those data blocks.
http://projects.theforeman.org/issues/17647
> Fixes #17647: add missing data-blocks to layout.

- app/assets/javascripts/bastion/layouts/partials/table.html
We are currently hiding filters if the table doesn't include the ability
to select rows, we should show filters in this case.
http://projects.theforeman.org/issues/17638
> Fixes #17638: show filters on non row select tables.

- app/assets/javascripts/bastion/components/views/bst-alert.html
The warning icon was using the wrong class and thus not being displayed,
this commit corrects the class.
http://projects.theforeman.org/issues/17688
> Fixes #17688: fix class for patternfly alert warning icon.

- app/assets/javascripts/bastion/components/views/bst-form-buttons.html
- app/assets/javascripts/bastion/components/views/bst-form-group.html
- app/assets/javascripts/bastion/components/views/bst-save-control.html
With non-nutupane we now have an excess of vertical space so we ought to
use regular boostrap 3 forms instead of horizontal forms.
http://projects.theforeman.org/issues/17385
> Fixes #17385: use normal BS3 forms instead of horizontal.

- app/assets/javascripts/bastion/components/bst-modal.directive.js
- app/assets/javascripts/bastion/components/views/bst-modal.html
- test/components/bst-modal.directive.test.js
Instead of requiring transclusion of a template, allow the modal
template to be specified via a template URL if desired.
http://projects.theforeman.org/issues/17848
> Fixes #17848: allow modal template url to be specified.

- app/assets/javascripts/bastion/routing.module.js
- test/routing.module.test.js
Removing the trailing slash from Pulp URLs breaks them so this change
adds an ignore list so we don't remove the trailing slash from these
URLs.
http://projects.theforeman.org/issues/17549
> Fixes #17549: add /pulp to list to not remove trailing slash.

- app/assets/javascripts/bastion/components/nutupane.factory.js
The nutupane factory was saving tables with a - at the beginning of the
name.  This commit removes the - at the front of the saved table name.
http://projects.theforeman.org/issues/17946
> Fixes #17946: remove preceding - from table cache name.

- app/assets/stylesheets/bastion/nutupane.scss
The color styles for table rows are too broad and cause the coloring in
row items (dropdowns, for example) to be incorrect.
http://projects.theforeman.org/issues/17945
> Fixes #17945: make color rules for table css less broad.

- app/assets/javascripts/bastion/components/nutupane.factory.js
- test/components/nutupane.factory.test.js
Also, zero out nutupane selected rows on refresh.
http://projects.theforeman.org/issues/18037
> Fixes #18037: provide a way to invalidate the table.

- app/assets/javascripts/bastion/layouts/details-page-with-breadcrumbs.html
- app/assets/javascripts/bastion/layouts/partials/page-header-with-actions.html
Use `<h1>` instead of `<h2>` in details page header and enforce `<h3>` in
sub-header.
http://projects.theforeman.org/issues/18038
> Fixes #18038: enforce consistent header weights. 

- app/assets/javascripts/bastion/components/nutupane.factory.js
- app/assets/javascripts/bastion/layouts/partials/table.html
Instead of making the user guess the first letter of the search they
want we should show the typeahead on initial focus.
http://projects.theforeman.org/issues/18243
> Fixes #18243: show typeahead on inital focus.

- app/assets/javascripts/bastion/routing.module.js
- test/routing.module.test.js
We were getting the relative url instead of an absolute url when
determining if a state transition should result in a 404 (which worked
until nutupane was removed).  This commit fixes the root url logic.
http://projects.theforeman.org/issues/15665
> Fixes #15665: get correct root url for 404 states.

- app/assets/javascripts/bastion/layouts/details-page-with-breadcrumbs.html
The sub-header angular-block was not being used because it was being
called from inside the content angular-block and was thus inaccessible.
However because of the `<h3>` surrounding the block it would cause spacing
issues on details pages.
http://projects.theforeman.org/issues/18160
> Fixes #18160: remove unused sub-header angular-block.

- lib/bastion/engine.rb
When we switched over to use foreman's copy of patternfly we also
removed the ability to include vendor css files into bastion. We should
revert this change so we can use vendor css files when needed.
http://projects.theforeman.org/issues/18306
> Fixes #18306: include vendor style sheets.

- app/assets/javascripts/bastion/layouts/partials/table.html
- app/assets/javascripts/bastion/utils/stop-event.directive.js
- test/utils/stop-event.directive.test.js
Add a directive that stops the propagation of an event to workaround
issue with inputs inside of ui-modals.
http://projects.theforeman.org/issues/18271
> Fixes #18271: add a stop event directive.

- app/assets/javascripts/bastion/components/bst-container-scroll.directive.js
Set the width of the container scroll wrapper to 100% + the width of the
browser scroll bar in order to ensure that the scroll happens outside of
the table rather than inside it.
http://projects.theforeman.org/issues/18162
> Fixes #18162: fix misaligned headers on table scroll

- app/assets/javascripts/bastion/layouts/partials/table.html
- app/assets/stylesheets/bastion/overrides.scss
- app/assets/stylesheets/bastion/tables.scss
Instead of displaying the search filters underneath the search we
should display them to the left of the search.
http://projects.theforeman.org/issues/18184
> Fixes #18184: move search filters to left of search.

- app/assets/javascripts/bastion/components/views/bst-bookmark.html
- app/assets/javascripts/bastion/components/views/bst-modal.html
Instead of assuming all modals have a .btn-danger we should allow the
confirm button to be specified.
http://projects.theforeman.org/issues/18937
> Fixes #18937: allow modal confirm button to be specified.

- app/assets/javascripts/bastion/components/views/bst-bookmark.html
The bookmark modal needs to use ng-form instead of a `<form>` element
because it appears within another form.  This fixes a JS error about the
controller for form not being found.
http://projects.theforeman.org/issues/18633
> Fixes #18633: use ng-form instead of <form> for bookmark.

- app/assets/javascripts/bastion/components/views/path-selector.html
The path selector was being provided an icon class for the text in the
suggested path selector.  This commit makes the icon class a separate
element instead of wrapping the text within the icon.
http://projects.theforeman.org/issues/19139
> Fixes #19139 fix incorrect font and weight in path selector.

- app/assets/stylesheets/bastion/overrides.scss
- app/assets/stylesheets/bastion/path-selector.scss
Ensure the rule for path selector unordered lists only applies to path
selector unordered lists.
http://projects.theforeman.org/issues/19167
> Fixes #19167: fix styling of unordered lists.

- app/assets/stylesheets/bastion/bastion.scss
- app/assets/stylesheets/bastion/components.scss
- app/assets/stylesheets/bastion/nutupane.scss
- app/assets/stylesheets/bastion/path-selector.scss
- app/assets/stylesheets/bastion/tables.scss
- app/assets/stylesheets/bastion/variables.scss
Instead of highlighting .info-blocks with the same color as tables we
should override the highlighting to be the normal page colors.
http://projects.theforeman.org/issues/18203
> Fixes #18203: override hover colors on .info-blocks.

- app/assets/javascripts/bastion/components/nutupane.factory.js
Ensure that the select all checkbox (and all selections) are removed
when the table is refreshed.
http://projects.theforeman.org/issues/18342
> Fixes #18342: unselect all when table is refreshed.

- grunt/karma.js
the previous 30 seconds does not seem to be sufficient
using 100s just as patternfly does
> Refs #19380 - adjust karma browserNoActivityTimeout

- app/assets/javascripts/bastion/components/bst-table.directive.js
- app/assets/javascripts/bastion/components/nutupane.factory.js
- app/assets/javascripts/bastion/layouts/partials/table.html
- test/components/nutupane.factory.test.js
Instead of showing the no rows message as an overused alert we should
just simply show it as a p.  Also we should show the total count of rows
so it's even more obvious that the table is empty.
http://projects.theforeman.org/issues/18404
Instead of this:
Do this:
> Fixes #18404: show no rows message inside table.

- app/assets/javascripts/bastion/components/nutupane.factory.js
- test/components/nutupane.factory.test.js
Adding a new flag overrideAutoLoad to control the initial loading behavior of the nutupane object.
This is required as in few use cases, we want to be able to set table parameters and adjust query parameters before loading the table.
> fixes #20368 - Host Collection/Host views not filtering correctly

- app/assets/javascripts/bastion/components/nutupane.factory.js
- test/components/nutupane.factory.test.js
The table on Bastion pages were blocking subsequent searches when there was a server side error.
Simple fix but required some adjustments to the Nutupane tests due to the introduction of the promise which broke 40+ specs.
> Fixes #20350 - Reset table refreshing state when fetching resource fails

- app/assets/javascripts/bastion/components/nutupane.factory.js
- app/assets/javascripts/bastion/layouts/partials/table.html
- test/components/nutupane.factory.test.js
If the API doesn't support pagination then we should not show the
pagination controls.
http://projects.theforeman.org/issues/20103
> Fixes #20103: hide pagination controls if no pagination.

- app/assets/javascripts/bastion/components/nutupane.factory.js
We are now catching errors in the nutupane load function. In our tests
(and possibly in custom tranformResponse functions) there is not a
$promise object so we should check for it before using it.
http://projects.theforeman.org/issues/20507
> Fixes #20507: check if $promise exists on resource before using it.

- app/assets/stylesheets/bastion/tables.scss
- app/assets/stylesheets/bastion/variables.scss
Links in highlighted rows weren't readable.  This commit fixes the links
so they are readable by changing the highlight color to the PF default.
http://projects.theforeman.org/issues/20530
Screenshots:
> Fixes #20530: ensure links in table are readable.

- app/assets/javascripts/bastion/components/nutupane.factory.js
- test/components/nutupane.factory.test.js
We should respect the state params for searches when an href is
generated with ui-sref. This commit ensures that $stateParams is
preferred over the table cache and what is in the query strings.
http://projects.theforeman.org/issues/20598
> Fixes #20598: use state params for search.

- bastion.gemspec
I can't really test this inside Katello, but the original issue should be fixed for a long time and according to the changelog, there were only additions of functionality and compatibility with newer Rails versions.
> update angular-rails-templates to 1.0.2

- app/assets/javascripts/bastion/components/nutupane.factory.js
The code was just dropping params rather than including the existing
global commands.
http://projects.theforeman.org/issues/20481
> Fixes #20481: Missing params on api call

- app/assets/javascripts/bastion/components/nutupane.factory.js
This keeps the URL from updating when change pagination options in a
modal. The modal state should be isolated and not update the URL.
http://projects.theforeman.org/issues/19949
> Fixes #19949: URL updating with modal changes

- app/assets/javascripts/bastion/components/views/bst-resource-switcher.html
The uib-dropdown has a bug where the focus gets stuck if you
have an anchor tag with an href attribute and uib-dropdown-toggle.
Removing the href solves the issue.
http://projects.theforeman.org/issues/21035
> Fixes #21035: Resource switcher intercepts focus

- README.md
- app/assets/javascripts/bastion/auth/auth.module.js
- app/assets/javascripts/bastion/bastion.module.js
- app/assets/javascripts/bastion/components/bst-bookmark.factory.js
- app/controllers/bastion/bastion_controller.rb
- app/views/bastion/layouts/assets.html.erb
- lib/bastion.rb
- test/bastion-config.test.js
- test/bastion/test-constants.js
This is only half of the change - there are changes required to each BastionResource in Katello and that'll be coming shortly. They do in fact need to be released together despite what I wrote here previously.
Few challenges:
- There is a *lot* of discussion in Rails and Angular communities on how to deploy those respective frameworks in subdirectories. At the end of the day we are constrained to the way [Foreman is doing it](https://github.com/theforeman/foreman/blob/1a0f69e7aac2e07fd438ca5ee3c2ef297b504242/config.ru#L6-L7).
- Lots (in katello) of BastionResource URLs prefixed with '/' which prevents 
-A bunch of templates broke thus the changes in the Bastion module
- Some Foreman routes present in Bastion layout were broken due to the way routes work within a rails engine. See comments …
> Refs #20732: Support subdirectory deployment

- app/assets/javascripts/bastion/components/bst-resource-switcher.directive.js
- app/assets/javascripts/bastion/components/views/bst-resource-switcher.html
The resource switcher should not be available when there is not
another resource to switch to or when creating a new resource.
http://projects.theforeman.org/issues/21054
> Fixes #21054: Hide resource switcher on new

- app/assets/javascripts/bastion/bastion.module.js
- app/views/bastion/layouts/assets.html.erb
- test/bastion/test-constants.js
The mark_active_menu function was removed from foreman with vertical
navigation. We should remove the usages of this from bastion as it
causes a JS error on all bastion pages
http://projects.theforeman.org/issues/21144
> Fixes #21144: remove mark_active_menu from bastion.

- app/assets/javascripts/bastion/components/nutupane.factory.js
- test/components/nutupane.factory.test.js
The table column sorting was broken when table caching was
implemented. This commit fixes the column soting.
http://projects.theforeman.org/issues/21416
> Fixes #21416: fix column sorting.

- app/controllers/bastion/bastion_controller.rb
- app/helpers/bastion/layout_helper.rb
- app/views/bastion/layouts/assets.html.erb
Adds possbility to specify :javascript and :stylesheet as a proc that is lazily evaluated from the assets layout.
Eg.:
```ruby
Bastion.register_plugin(
:name => 'bastion_katello',
:javascript => Proc.new {
[
javascript_include_tag(*webpack_asset_paths('katello', :extension => 'js'), "data-turbolinks-track" => true),
javascript_include_tag('bastion_katello/bastion_katello')
]
},
```
> Fixes #21311 - Allow adding multiple js and style tags from plugins

- package.json
Setting the root for eslint so it stops cascading.
See https://eslint.org/docs/user-guide/configuring
http://projects.theforeman.org/issues/21631
> Fixes #21631 - Set root for eslint

- eslint.yaml
- package.json
Moving the root flag from package.json to eslint.yaml
http://projects.theforeman.org/issues/21632
> Fixes #21632 - Move root to eslint.yaml

- app/controllers/bastion/bastion_controller.rb
This makes Katello work for me again on the latest develop.
> fixes #22118 - Replace skip_before_filter with skip_before_action for Rails 5

- app/assets/javascripts/bastion/components/nutupane.factory.js
The next page button was not working on the errata page (and
potentially others).  This commit ensures that the table cache
is invalidated when changing pages.
http://projects.theforeman.org/issues/22134
> Fixes #22134: fix next page not working.

- app/assets/javascripts/bastion/components/nutupane.factory.js
For some reason params.page was not being set correctly on load
but table.params.page was.  This commit ensures that params.page
is set.
http://projects.theforeman.org/issues/22134
> Fixes #22134: set params.page correctly.

- app/assets/javascripts/bastion/components/nutupane.factory.js
1. Create a new Content View
2. Create a new CCV
3. Add the CV in CCV
4. Remove the CV from the CCV.
4. The CV will not be on the Add list. 
There are several other flows which would cause the same issue.
In the method loadParamsFromExistingTable we could either assign self.table.params to params or make existingTable.params the target param for the _.extend method.
> Fixes #23120 - CV Add on Composite CV refresh issue

- app/assets/javascripts/bastion/components/bst-resource-switcher.directive.js
- app/assets/javascripts/bastion/layouts/partials/table.html
- test/components/bst-resource-switcher.directive.test.js
Tracking 3 related issues here:
1. Provide ability to show/hide Resource Switcher. (For pages where breadcrumb is needed but the resource switcher is not. Ex: Repo Discovery)
2. Fix _"[DOM] Found 2 elements with non-unique id #currentPage"_ console error on certain pages on the input box **_Page number_** of total Page (Example Product> Repo Discovery)
3. Fix _"TypeError: Cannot read property '0' of null"_ on pages where path doesn't have ids (Example Product> Repo Discovery, Content Host> Register)
> Fixes #23434 - Show/Hide Resource Switcher and fix duplicate Id error

- app/assets/javascripts/bastion/bastion-bootstrap.js
- app/assets/javascripts/bastion/components/bst-edit.directive.js
We are adding editTrigger to text field and forcedWorkingMode to bst-edit-select.
We need these for some UI changes needed for https://github.com/Katello/katello/pull/7644
> Fixes #24729 - Allow edit trigger on text etc

- app/assets/javascripts/bastion/bastion-bootstrap.js
- app/assets/javascripts/bastion/components/nutupane.factory.js
This is related to PR: https://github.com/Katello/bastion/pull/227.
The issue is that the new changes do not update the nutupane params with the table params. 
The issue presents itself on the repository sets tab on content host and activation keys.
For more details, see : https://github.com/Katello/katello/pull/7652
- Go to activation key / Content Host
- Go to Repository sets tab. (You should see records if there are subscriptions attached)
- Click on show all.
- All repository sets are not displayed, especially if you go to some other tab on the page and come back.
> Fixes #24725 - need to set nutupane params correctly

- app/assets/javascripts/bastion/components/bst-edit.directive.js
From the katello side we are looking at values which don't have ids:
```
[
{name: 'EUS', selected: true}
]
```
This change makes it so checkprevious won't attempt to process values like this so the code will honor the given 'selected' value. We could also opt to remove the checkPrevious stuff altogether since it's used in just one  place in Katello where were aren't relying on it - but this preserves existing behavior in the test.
> Fixes #25083 - Ignore missing ids when checking previous values

- app/assets/javascripts/bastion/components/nutupane.factory.js
- test/components/nutupane.factory.test.js
It appears we were misusing `_.extend`: https://lodash.com/docs/4.17.10#assignIn
We want to update the params, not the existingTable.params (the existingTable.params have the recently user-input per_page value).
Note how the test fails without the code change.
Note also that your queries are now saved on each table. If you set a per_page of 25 and `search='name~c'` on package list, then click the errata tab, set per_page to something, and then go back to the packages table, all your params are still set!
> Fixes #24554: Xtnd params not existingTable.params

- app/assets/javascripts/bastion/components/notification.service.js
- test/components/notification.service.test.js
This is my first attempt at fixing this code. I'm getting it to work correctly to fix the issue, but it's causing some weird problems with other success notification windows. It seems to stall the process of showing the notification window and any action after that.
Also, I'm getting hung up with the tests that I wrote. I'm unsure of how to pass the parameters correctly and use the default parameters when only a message is passed to the function. Failing tests look like so: 
```
PhantomJS 2.1.1 (Linux 0.0.0) Factory: Nofification provides a way to set success messages FAILED
TypeError: undefined is not an object (evaluating 'options.context') in /home/vagrant/bastion/app/assets/javascripts/bastion/components/notification.service.js (line 9) …
```
> Fixes #25047 - Notification link

- app/assets/stylesheets/bastion/forms.scss
I removed the .editable-value class from the stylesheet when working on system purpose since it was distorting the view with the additional changes I was making - this broke the display of GPG keys under Content Credentials as a result.
Adding this class back not only fixes the GPG key display, but it seems to have no issue with the System Purpose display on Content Host Details which I had observed earlier...
create a content credential for a GPG key such as https://getfedora.org/static/429476B4.txt
Observe that viewing the key results in the newlines not being properly respected
Applying the patch will correct the problem and the key will display as it is in the above .txt
The local bastion setup can be achieved like this for a bastion checkout in /home/vagrant/bastion
``` …
```
> Fixes #25372 - Restore .editable-value class
