app/assets/javascripts/bastion/layouts/nutupane.html
app/assets/stylesheets/bastion/nutupane.less

http://projects.theforeman.org/issues/9053
http://projects.theforeman.org/issues/9039

Fixes #9053, #9039: move filter block to its own line above search.

---

app/assets/javascripts/bastion/components/bst-modal.directive.js
app/assets/javascripts/bastion/components/views/bst-modal.html

http://projects.theforeman.org/issues/9474

Refs #9474: add ability to specify confirm button text to bst-modal.

---

app/assets/javascripts/bastion/components/bst-modal.directive.js
app/assets/javascripts/bastion/components/views/bst-modal.html
test/components/bst-modal.directive.test.js

http://projects.theforeman.org/issues/9484

Refs #9484: use angular blocks to allow translation of modals.

---

app/assets/stylesheets/bastion/nutupane.less

http://projects.theforeman.org/issues/9342
https://bugzilla.redhat.com/show_bug.cgi?id=1191723

Fixes #9342: fix wrapping for nutupane info-{label,value}, BZ1191723

---

app/assets/javascripts/bastion/components/path-selector.directive.js
app/assets/javascripts/bastion/components/views/path-selector.html

http://projects.theforeman.org/issues/9549
https://bugzilla.redhat.com/show_bug.cgi?id=1195972

Fixes #9549: ensure checkbox is clickable on path selector, BZ1195972.

---

app/assets/javascripts/bastion/layouts/details-nutupane.html
app/assets/javascripts/bastion/layouts/nutupane.html

http://projects.theforeman.org/issues/9853
http://projects.theforeman.org/issues/9839
https://bugzilla.redhat.com/show_bug.cgi?id=1203851
See also Katello/katello#5122.

Fixes #9853, refs #9839: add no items message to nutupane, BZ 1203851.

---

app/assets/javascripts/bastion/auth/auth.module.js

http://projects.theforeman.org/issues/9874
https://bugzilla.redhat.com/show_bug.cgi?id=1118444

Fixes #9874: prevent redirection to API calls, BZ1118444.

---

app/assets/javascripts/bastion/auth/auth.module.js

The permission check will indicate permitted if any of the permissions
supplied are met.

Fixes #10147: Handle arrays of permissions.

---

app/assets/javascripts/bastion/components/views/path-selector.html

Allows for highlighting of specific environments along a path.

fixes #10351 - adds capability to put an icon prior to environment name in path selector

---

config/routes.rb

http://projects.theforeman.org/issues/10971

Fixes #10971: upgrade bastion to rails4.

---

app/assets/stylesheets/bastion/nutupane.less

http://projects.theforeman.org/issues/11875
https://bugzilla.redhat.com/show_bug.cgi?id=1203034

Fixes #11875: make buttons legible on highlighted row, BZ1203034.

---

app/assets/javascripts/bastion/utils/urlencode.filter.js
test/utils/urlencode.filter.test.js

http://projects.theforeman.org/issues/13299

Fixes #13299:  add urlencode filter.

---

README.md

http://projects.theforeman.org/issues/13320

Fixes #13320:  add information about releasing bastion to readme.

---

app/assets/javascripts/bastion/components/nutupane.factory.js

this is needed for https://github.com/Katello/katello/pull/5819/

Fixes #13952 - Report scoped search errors

---

app/assets/javascripts/bastion/components/nutupane.factory.js
test/components/nutupane.factory.test.js

http://projects.theforeman.org/issues/14108

Fixes #14108: close nutupane item view when org switcher is used.

---

app/assets/javascripts/bastion/utils/urlencode.filter.js

http://projects.theforeman.org/issues/14148

Fixes #14148: use minification safe syntax for urlencoder filter.

---

app/assets/javascripts/bastion/components/bst-alert.directive.js
app/assets/javascripts/bastion/components/components.module.js
app/assets/stylesheets/bastion/animations.scss

http://projects.theforeman.org/issues/14671

Fixes #14671:  fade out success messages after 5 seconds.

---

app/assets/javascripts/bastion/components/views/autocomplete-scoped-search.html

Fixes #15303 - Show special characters in autocomplete fields

---

app/assets/javascripts/bastion/bastion.module.js

http://projects.theforeman.org/issues/15616

Fixes #15616: don't interfere with any organization link.

---

app/assets/javascripts/bastion/components/nutupane.factory.js
app/assets/javascripts/bastion/layouts/nutupane.html

When the search results are empty, a message can be set using data-block="no-search-results-message"

Refs #14271 - Set message for empty search results

---

app/assets/javascripts/bastion/auth/auth.module.js
app/assets/javascripts/bastion/auth/authorization.service.js
app/assets/javascripts/bastion/bastion-bootstrap.js
app/assets/javascripts/bastion/bastion.js
app/assets/javascripts/bastion/bastion.module.js
app/assets/javascripts/bastion/components/components.module.js
app/assets/javascripts/bastion/components/current-tasks.directive.js
app/assets/javascripts/bastion/i18n/i18n.module.js
app/assets/javascripts/bastion/menu/menu.module.js
app/assets/javascripts/bastion/routing.module.js
app/assets/javascripts/bastion/utils/bastion-resource.factory.js
app/assets/javascripts/bastion/utils/utils.module.js
app/views/bastion/layouts/application.html.erb
app/views/bastion/layouts/assets.html.erb
grunt/karma.js
test/auth/authorization.service.test.js
test/bastion/test-constants.js
test/components/bst-bookmark.factory.test.js
test/routing.module.test.js
test/utils/bastion-resource.factory.test.js

Adding an additional check to ensure that a potential 404 is valid.
This issue can be encountered if the state's url doesn't match its name.
http://projects.theforeman.org/issues/15665

Fixes #15665: ensure parent state url matches before 404.

---

app/assets/javascripts/bastion/components/nutupane.factory.js
app/assets/javascripts/bastion/layouts/details-nutupane.html
app/assets/javascripts/bastion/layouts/nutupane.html
app/assets/stylesheets/bastion/nutupane.scss
test/components/nutupane.factory.test.js

http://projects.theforeman.org/issues/15842
Note that the design change to this follows [patternfly's search widget](https://www.patternfly.org/pattern-library/widgets/#search)

Fixes #15842: move 'x' into search field on nutupane pages.

---

bower.json
grunt/karma.js
test/routing.module.test.js
vendor/assets/javascripts/bastion/angular-ui-router/angular-ui-router.js

http://projects.theforeman.org/issues/16667

Fixes #16667:  Upgrade angular-ui-router.

---

app/assets/stylesheets/bastion/variables.scss

http://projects.theforeman.org/issues/17452

Fixes #17452: increase padding on pages.

---

app/assets/javascripts/bastion/components/nutupane.factory.js
app/assets/javascripts/bastion/components/table-cache.service.js
test/components/table-cache.service.test.js

Save the table state for each table so it is preserved between state
changes.
http://projects.theforeman.org/issues/17096

Fixes #17096: remember table state.

---

app/assets/javascripts/bastion/components/bst-modal.directive.js
app/assets/javascripts/bastion/components/components.module.js
app/assets/javascripts/bastion/components/views/autocomplete-scoped-search.html
app/assets/javascripts/bastion/components/views/bst-alert.html
app/assets/javascripts/bastion/components/views/bst-dropdown.html
app/assets/javascripts/bastion/components/views/current-tasks.html
app/assets/javascripts/bastion/layouts/details-nutupane.html
app/assets/javascripts/bastion/layouts/nutupane.html
app/assets/javascripts/bastion/layouts/partials/table.html
app/assets/stylesheets/bastion/overrides.scss
bower.json
test/components/bst-bookmark.directive.test.js
test/components/bst-dropdown.directive.test.js
test/components/bst-modal.directive.test.js
vendor/assets/javascripts/bastion/angular-bootstrap/ui-bootstrap-tpls.js
vendor/assets/javascripts/bastion/angular-bootstrap/ui-bootstrap.js

http://projects.theforeman.org/issues/16977

Fixes #16977: upgrade ui-bootstrap to 2.3.1

---

app/assets/javascripts/bastion/components/table-cache.service.js
test/components/table-cache.service.test.js

http://projects.theforeman.org/issues/17940

Fixes #17940: add mechanism to remove tables from the cache.

---

app/assets/javascripts/bastion/components/nutupane.factory.js

http://projects.theforeman.org/issues/17947

Fixes #17947: remove table from cache on refresh.

---

app/assets/javascripts/bastion/components/nutupane.factory.js

We need to temporarily disable the table cache until we figure out the
best way to invalidate the cache and where.
http://projects.theforeman.org/issues/18079

Fixes #18079: temporarily disable table cache.

---

app/assets/javascripts/bastion/components/nutupane-table.directive.js
app/assets/javascripts/bastion/layouts/partials/table.html
app/assets/stylesheets/bastion/bastion.scss
app/assets/stylesheets/bastion/components.scss
app/assets/stylesheets/bastion/overrides.scss
app/assets/stylesheets/bastion/tables.scss

Instead of maintaining our own set of rules for tables under
.nutupane we should be using the classes from patternfly.
http://projects.theforeman.org/issues/18030

Fixes #18030: use patternfly table classes.

---

app/assets/stylesheets/bastion/overrides.scss

http://projects.theforeman.org/issues/18241

Fixes #18241: fix datepicker and typeahead dropdown css.

---

app/assets/stylesheets/bastion/tables.scss

http://projects.theforeman.org/issues/18158

Fixes #18158: ensure that long columns wrap on small screens.

---

app/assets/javascripts/bastion/bastion.js
bower.json
vendor/assets/javascripts/bastion/angular-patternfly/angular-patternfly.js

http://projects.theforeman.org/issues/17689

Fixes #17689: include angular-patternfly into bastion.

---

app/views/bastion/layouts/assets.html.erb

For use with https://github.com/Katello/katello/pull/6701

fixes #19008 - flag indication full access mode

---

app/assets/stylesheets/bastion/tables.scss
app/assets/stylesheets/bastion/variables.scss

We can use this variable in the css for
https://github.com/Katello/katello/pull/6698

Refs #18990 - Create variable for table row-select width

---

test/bastion/test-constants.js

http://projects.theforeman.org/issues/19072

Fixes #19072: add entriesPerPage to list of test constants.

---

app/assets/javascripts/bastion/utils/disable-link.directive.js
test/utils/disable-link.directive.test.js

Add a directive that prevents links from being clicked.
http://projects.theforeman.org/issues/19090

Fixes #19090: add directive to disable links.

---

app/assets/javascripts/bastion/components/nutupane.factory.js
app/assets/javascripts/bastion/layouts/partials/table.html
test/components/nutupane.factory.test.js

http://projects.theforeman.org/issues/19071

Fixes #19071: ensure page exists before changing page.

---

app/assets/javascripts/bastion/components/views/bst-save-control.html

http://projects.theforeman.org/issues/18451

Fixes #18451: ensure spinner isn't shown on load.

---

app/assets/javascripts/bastion/components/nutupane.factory.js
test/components/nutupane.factory.test.js

Cache the page number, sort, search, etc. on tables so they are
preserved upon state change.
http://projects.theforeman.org/issues/18485

Fixes #18485: add table parameter caching

---

app/assets/javascripts/bastion/components/bst-resource-switcher.directive.js
app/assets/javascripts/bastion/components/views/bst-resource-switcher.html
app/assets/javascripts/bastion/layouts/partials/full-row-breadcrumbs.html
app/assets/javascripts/bastion/layouts/partials/table.html
app/assets/stylesheets/bastion/components.scss
app/assets/stylesheets/bastion/overrides.scss
test/components/bst-resource-switcher.test.js
test/components/nutupane.factory.test.js

This commit adds the ability to quickly switch between resources
of the same type.
http://projects.theforeman.org/issues/18080

Fixes #18080: add resource switcher to bastion.

---

app/assets/javascripts/bastion/components/bst-resource-switcher.directive.js
app/assets/javascripts/bastion/components/views/bst-resource-switcher.html
test/components/bst-resource-switcher.directive.test.js

http://projects.theforeman.org/issues/21483

Fixes #21483: highlight current item in resource switcher.

---

app/views/bastion/layouts/assets.html.erb
test/bastion/test-constants.js

http://projects.theforeman.org/issues/21076

Fixes #21076: add unregister_delete_host setting.

---

bastion.gemspec

* Corrects the homepage
* Sets the license
* Trims trailing whitespace

Fixes #23664 - Update the gemspec

---

app/assets/javascripts/bastion/components/formatters/array-to-string.filter.js
app/assets/javascripts/bastion/components/views/bst-edit-multiselect.html
test/components/formatters/array-to-string.filter.test.js

arrayToString was oddly expecting an object, and this refactors mutliselect to be useful for my purposes. Neither of these appear to be used anywhere in Katello at the moment.

fixes #25035 - refactor multiselect and fix arrayToString

---

app/assets/javascripts/bastion/bastion.module.js

This reverts commit 56fa81fbe9be8adf349b410e3b42b471be48654c.

Revert "provide repo types on rootScope"

---

bower.json
grunt/karma.js

https://projects.theforeman.org/issues/25772

Fixes #25772: add ngReact to test includes.

---

grunt/karma.js

https://projects.theforeman.org/issues/25772

Fixes #25772: correct path of ngReact.

---

app/assets/javascripts/bastion/components/bst-edit.directive.js
app/assets/javascripts/bastion/components/views/bst-edit-save-cancel.html

Add an option to set custom working text on save/cancel work mode.

Fixes #26248 - Add custom working text
